services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80" 
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      SUBDOMAIN: ${USER_NAME}
      DB_PATH: ${DB_PATH}
    volumes:
      - ./backend/db/aplikasi.db:/app/db/aplikasi.db
    networks:
      - webnet
  
  proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      SUBDOMAIN: ${USER_NAME}
    networks:
      - webnet

networks:
  webnet:
